title: dave-wiki
description: wikipage
show_downloads: true
git_branch: gh-pages
logo_url:
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: false
google_cse_token: 
custom_head: true
custom_sidebar: true
custom_footer: true

show_downloads: false

gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
